project:
  type: website
  output-dir: docs

website:
  title: "LabGeo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Historia/sobre.qmd
        text: Historia
      - href: Estagiarios/Estagiarios.qmd
        text: Estagiários

      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


