project:
  type: website
  output-dir: docs

website:
  title: "LabGeo"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Historia/sobre.qmd
        text: Historia
      - href: Estagiarios/Estagiarios.qmd
        text: Pos
      - href: pos/pos.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


