project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by LabGeo."
  navbar:
    title: false
    logo: imagens/Labgeo.png
    right:
      - href: index.qmd
        text: Home
      - href: Historia/sobre.qmd
        text: História
      - href: Integrantes/Estagiarios.qmd
        text: Integrantes
      - href: publicacao.qmd
        text: Publicação
      

format:
  html:
    page-layout: full
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true
