project:
  type: website
  output-dir: docs

website:
  navbar:
    title: false
    logo: imagens/Labgeo.png
    right:
      - href: index.qmd
        text: Home
      - href: Historia/sobre.qmd
        text: Historia
      - href: Estagiarios/Estagiarios.qmd
        text: Estagiario
      - href: pos/pos.qmd
        text: Pos
      

format:
  html:
    page-layout: full
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true
